### ISSUE TITLE
Unidentified 15 in logs

### ISSUE THREAD

**Issue by theofidry** [abstractvector/node-dbf#12]
I've tried the following code:

```javascript
myFunction: function (req, res) {

      var uploadedFile = req.files['fileId'],
      var parser = new Parser(uploadedFile.path);
      parser.parse();
```

And I've got a mysterious `15` appearing in my console. If I comment the `parser.parse()` line it does no longer display the `15` so this is really coming from the parser.

**Comment by dimfeld** [comment]
This is probably coming from the parseDate function. See https://github.com/abstractvector/node-dbf/blob/master/src/header.coffee#l23. PR #13 eliminates this as well as making other changes.

**Comment by theofidry** [comment]
Ok thanks.
