### ISSUE TITLE
Isn't it time to publish a fresh version on npmjs.org?

### ISSUE THREAD

**Issue by irandom** [abstractvector/node-dbf#15]
3 years has passed since last update. E.g., I was forced to add the updated source of node-dbf into my product repository. It would be better to just add a Node dependency and get 0.1.1 from the net.

**Comment by irandom** [comment]
Seems to be fixed in bcf8fa52c72dd169d12f1a40ef01cba5c56a8a0f. Licence is added as well, it was long expected thing to do, thanks!

**Comment by abstractvector** [comment]
Sorry it took so long - somehow I wasn't receiving notifications on this library. I'm going to be adding some new features (and tests) over the coming weeks. I'll make sure to push new versions to npmjs as I go.
