### ISSUE TITLE
@deleted condition is incomplete

### ISSUE THREAD

**Issue by HumanSprout** [abstractvector/node-dbf#23]
I noticed that the '@deleted' property in the record objects was not always accurate (possibly related to
[this issue](https://github.com/abstractvector/node-dbf/issues/11))

I found in the [.DBF specification](http://www.clicketyclick.dk/databases/xbase/format/dbf.html#DBF_STRUCT) (and confirmed) that the deleted flag could have one of four different values: 20h, 2Ah, '*', and " " (blank).

The assignment for `record['@deleted']` in lib/parser.js was only accounting for one. I fixed this by (locally) changing the assignment to:

`'@deleted': ( (buffer.slice(0, 1))[0] === 42 || (buffer.slice(0, 1))[0] === '*' ) ? true : false,`

I hope this helps

**Comment by forrestmid** [comment]
I can verify this is an issue with the current version. Replacing the line on the parser.js file fixed the data I was trying to import from a DBF file using a star (*) as the deleted flag.

**Comment by abstractvector** [comment]
Can you issue a pull request with a sample file so I can fix this and create the test for it please?

**Comment by abstractvector** [comment]
Closing this per the discussion in https://github.com/abstractvector/node-dbf/pull/31
