### ISSUE TITLE
parses float as integer

### ISSUE THREAD

**Issue by srikpreethy** [abstractvector/node-dbf#24]
I am using node-dbf version 0.2.1
I have float values (including negative values) in my dbf file. Its getting parsed as integer.

**Comment by mikhailrojo** [comment]
find the same problem
is it sees type N - > it parses as Int
it it sees type А -> it parses as Float

I changed by hand package node_modules/node-dbf/lib/parser line #109- 113
to treat N as Float
good luck

**Comment by abstractvector** [comment]
Fixed
